# Chapter 3. 데이터 다루기

## 1. 파이썬 문법에 대한 이해

### 1-3. 함수

In [1]:
# 사용자 정의 함수 my_calc
def my_calc(a, b):
    c = a*2 + b
    print(c)

In [2]:
my_calc(1, 2)

4


### 1-4. 조건문

In [3]:
a = 0.3

In [4]:
# a가 0.5보다 작으면 0, 0.5보다 크면 1을 출력
if a < 0.5 :
    print(0)
else :
    print(1)

0


### 1-5. 반복문

In [5]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
b = [ ]

In [7]:
for i in range(10) :
    b.append(i)

### 1-6. 자료형

In [8]:
type(1)

int

In [9]:
type(1.2)

float

In [10]:
type(1+2j)

complex

In [11]:
type('setosa')

str

In [12]:
type([200, 'setosa', 5.947])

list

In [13]:
type((200, 'setosa', 5.947))

tuple

In [14]:
type(True)

bool

In [15]:
type({200, 'setosa', 5.947})

set

In [16]:
type({'name' : 'Jon Snow', 'family' : 'Stark'})

dict

---

## 2. pandas의 데이터 프레임

### 2-1. 데이터 프레임이란? (iris 데이터 셋 불러오기)

> iris 데이터 셋의 특징
<div>
<img src="https://python.astrotech.io/_images/dataset-iris-flowers.png" width="500"/>
</div>

>iris 데이터 셋이 데이터 분석 교육용으로 가장 널리 사용되는 이유는 수치형(Numerical) 데이터뿐만 아니라 붓꽃의 종류라는 범주형(Categorical) 데이터까지 존재해 회귀(Regression)와 분류(Classification) 문제 모두를 실습해 볼 수 있기 때문입니다.

In [17]:
# pandas 패키지 불러오기 및 pd라는 약어로 지칭하기
import pandas as pd  
# sklearn 패키지의 datasets 모듈에서 load_iris 함수 불러오기
from sklearn.datasets import load_iris

In [18]:
iris = load_iris()  # iris 변수에 iris 데이터셋 입력

In [19]:
# iris 데이터셋의 독립변수(feature) 이름 및 데이터 출력
print(iris.feature_names)
print(iris.data)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3

In [20]:
# iris 데이터셋의 종속변수(target) 이름 및 데이터 출력
print(iris.target_names)
print(iris.target)

['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


> ※ 함수와 메서드  
메서드(method)는 객체(object)에 속하는 함수(function)를 뜻합니다. 예를들어, 아래 사례의 경우 head()를 사용할 때 df 다음에 “.” 점을 찍고 head()를 사용했습니다. df가 객체이기 때문에 이 경우 head()는 메서드라고 부릅니다. 다만, 메서드는 결국 함수의 부분집합이기 때문에 함수라고 불러도 틀린 말은 아닙니다.

In [21]:
# iris.data 데이터셋 타입 확인
type(iris.data)

numpy.ndarray

In [22]:
# 다차원배열(ndarray) 타입의 iris.data를 pandas 패키지를 이용해 데이터 프레임으로 변경
df = pd.DataFrame(data = iris.data, columns = iris.feature_names)

In [23]:
# df 데이터셋에 species 열을 추가하고 iris.target을 추가
df['species'] = iris.target

In [24]:
# head() 메서드를 이용해 df 데이터셋의 상위 5개 데이터만 출력
df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

>※ 데이터프레임 형태의 iris 데이터 셋을 바로 불러오는 방법  
seaborn 패키지의 load_dataset('iris')를 이용하면 됩니다.  
(예시)  
import seaborn as sns  
iris = sns.load_dataset('iris')  
iris.head()

### 2-2. 데이터 프레임 다루기

#### ① 열 이름 변경하기

In [25]:
# df 데이터 셋의 컬럼명 확인
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'species'],
      dtype='object')

In [26]:
# 컬럼명 변경
df.columns = ['sl','sw','pl','pw','sp']

In [27]:
df.head(5)

sl   sw   pl   pw  sp
0  5.1  3.5  1.4  0.2   0
1  4.9  3.0  1.4  0.2   0
2  4.7  3.2  1.3  0.2   0
3  4.6  3.1  1.5  0.2   0
4  5.0  3.6  1.4  0.2   0

In [28]:
# 5번째 컬럼명만 sp에서 s로 변경
df.rename(columns = {'sp' : 's'}, inplace = True)

In [29]:
df.head(5)

sl   sw   pl   pw  s
0  5.1  3.5  1.4  0.2  0
1  4.9  3.0  1.4  0.2  0
2  4.7  3.2  1.3  0.2  0
3  4.6  3.1  1.5  0.2  0
4  5.0  3.6  1.4  0.2  0

#### ② 특정 데이터만 추출하기

In [30]:
# df 데이터프레임의 데이터 확인
df.values

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

>※ pandas의 속성(attribute)  
속성(attribute)은 함수(function)와 변수(variable) 형태로 나뉘며 앞서 설명한 head()의 경우는 함수 형태로 이를 메서드(method)라고 불렀습니다. pandas에서 ()가 붙지 않는 변수 형태의 columns, index, dtypes, values, shape 등은 속성(attribute)이라고 부릅니다.

In [31]:
# df 데이터프레임의 열 인덱스 확인
df.columns

Index(['sl', 'sw', 'pl', 'pw', 's'], dtype='object')

In [32]:
# df 데이터프레임의 행 인덱스 확인
df.index

RangeIndex(start=0, stop=150, step=1)

>※ 인덱싱(indexing), 슬라이싱(slicing)  
파이썬에서는 인덱싱과 슬라이싱이라는 용어를 많이 사용합니다. 인덱싱은 개별 요소만 얻고자 할 때, 슬라이싱은 연속적인 요소를 얻고자 할 때 사용합니다. 즉, 슬라이스 기호(:)를 이용해 범위의 개념이 들어가면 슬라이싱인 것입니다. 다만 이 책에서는 인덱싱, 슬라이싱이라는 용어보다는 원하는 데이터만 뽑아서 추출한다는 뜻에서 보다 범용적인 필터링(filtering)이라는 용어를 주로 사용합니다.


#### ②-1 데이터프레임 행 필터링

In [33]:
# df 데이터프레임에서 0~3번째 행의 데이터만 불러오기
df[0:4]

sl   sw   pl   pw  s
0  5.1  3.5  1.4  0.2  0
1  4.9  3.0  1.4  0.2  0
2  4.7  3.2  1.3  0.2  0
3  4.6  3.1  1.5  0.2  0

In [34]:
# df 데이터프레임에서 3번째 행의 데이터만 불러오기
df[3:4]

sl   sw   pl   pw  s
3  4.6  3.1  1.5  0.2  0

#### ②-2 데이터프레임 열 필터링

In [35]:
# df 데이터프레임에서 sl 열의 데이터만 불러오기
df['sl']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sl, Length: 150, dtype: float64

In [36]:
# df 데이터프레임에서 sl, pl, s 열의 데이터만 불러오기
df[['sl','pl','s']]

sl   pl  s
0    5.1  1.4  0
1    4.9  1.4  0
2    4.7  1.3  0
3    4.6  1.5  0
4    5.0  1.4  0
..   ...  ... ..
145  6.7  5.2  2
146  6.3  5.0  2
147  6.5  5.2  2
148  6.2  5.4  2
149  5.9  5.1  2

[150 rows x 3 columns]

#### ②-3 데이터프레임 행&열 동시 필터링

In [37]:
# 3째 행까지 sl, s 열의 데이터만 불러오기
df[0:4][['sl','s']]

sl  s
0  5.1  0
1  4.9  0
2  4.7  0
3  4.6  0

#### ②-4 데이터프레임 행&열 동시 필터링(loc)

In [38]:
# 3째 행까지 sl, s 열의 데이터만 불러오기
df.loc[0:3,('sl','s')]

sl  s
0  5.1  0
1  4.9  0
2  4.7  0
3  4.6  0

#### ②-5 데이터프레임 행&열 동시 필터링(iloc)

In [39]:
# 3째 행까지 sl, s 열의 데이터만 불러오기
df.iloc[0:4,[0, 4]]

sl  s
0  5.1  0
1  4.9  0
2  4.7  0
3  4.6  0

#### ②-6 데이터프레임 인덱스 활용 4가지 데이터 셋 만들기

#### Case 1. s가 1인 대상만 추출

In [40]:
# df 데이터 셋에서 컬럼 s가 1인 대상만 추출해 df_1에 넣음
df_1 = df[df.s == 1]

In [41]:
# 데이터프레임의 경우 info() 함수를 이용해 데이터 셋 정보 확인 가능
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 50 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   sl      50 non-null     float64
 1   sw      50 non-null     float64
 2   pl      50 non-null     float64
 3   pw      50 non-null     float64
 4   s       50 non-null     int32  
dtypes: float64(4), int32(1)
memory usage: 2.1 KB


In [42]:
# tail() 함수를 이용하면 끝에서부터 위로 원하는 행만큼 조회 가능
df_1.tail(5)

sl   sw   pl   pw  s
95  5.7  3.0  4.2  1.2  1
96  5.7  2.9  4.2  1.3  1
97  6.2  2.9  4.3  1.3  1
98  5.1  2.5  3.0  1.1  1
99  5.7  2.8  4.1  1.3  1

#### Case 2. sl이 6보다 크고, s가 1인 대상만 추출

In [43]:
# df 데이터 셋에서 sl이 6보다 크고, s가 1인 대상만 추출해 df_2에 넣음
df_2 = df[(df.sl > 6) & (df.s == 1)]

In [44]:
df_2

sl   sw   pl   pw  s
50  7.0  3.2  4.7  1.4  1
51  6.4  3.2  4.5  1.5  1
52  6.9  3.1  4.9  1.5  1
54  6.5  2.8  4.6  1.5  1
56  6.3  3.3  4.7  1.6  1
58  6.6  2.9  4.6  1.3  1
63  6.1  2.9  4.7  1.4  1
65  6.7  3.1  4.4  1.4  1
68  6.2  2.2  4.5  1.5  1
71  6.1  2.8  4.0  1.3  1
72  6.3  2.5  4.9  1.5  1
73  6.1  2.8  4.7  1.2  1
74  6.4  2.9  4.3  1.3  1
75  6.6  3.0  4.4  1.4  1
76  6.8  2.8  4.8  1.4  1
77  6.7  3.0  5.0  1.7  1
86  6.7  3.1  4.7  1.5  1
87  6.3  2.3  4.4  1.3  1
91  6.1  3.0  4.6  1.4  1
97  6.2  2.9  4.3  1.3  1

#### Case 3. s가 0인 대상에서 sl, sw, s 열만 추출

In [45]:
# df 데이터 셋에서 s가 0인 대상의 sl, sw, s 열만 추출해 df_3에 넣음
df_3 = df.loc[df.s == 0, ['sl','sw','s']]

In [46]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   sl      50 non-null     float64
 1   sw      50 non-null     float64
 2   s       50 non-null     int32  
dtypes: float64(2), int32(1)
memory usage: 1.4 KB


#### Case 4. s 열만 제외하고 추출

In [47]:
# df 데이터 셋에서 s 열만 제외하고 추출해 df_4에 넣음
df_4 = df[df.columns.difference(['s'])]

In [48]:
df_4.head(5)

pl   pw   sl   sw
0  1.4  0.2  5.1  3.5
1  1.4  0.2  4.9  3.0
2  1.3  0.2  4.7  3.2
3  1.5  0.2  4.6  3.1
4  1.4  0.2  5.0  3.6

---

## 3. numpy의 다차원 배열

### 3-1. 다차원 배열이란?

In [49]:
# numpy 패키지 불러오기 및 np라는 약어로 지칭하기
import numpy as np

In [50]:
# 스칼라
a0 = np.array(1)
a0

array(1)

In [51]:
# 벡터
a1 = np.array([1, 2])
a1

array([1, 2])

In [52]:
# 행렬
a2 = np.array([[1, 2],[3, 4]])
a2

array([[1, 2],
       [3, 4]])

In [53]:
# 텐서
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [2, 4, 8]]])
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 4, 8]]])

In [54]:
# ndim 속성을 이용해 배열의 차원 확인
print(a0.ndim, a1.ndim, a2.ndim, a3.ndim)

0 1 2 3


In [55]:
# shape 속성을 이용해 배열의 크기 확인
print(a0.shape, a1.shape, a2.shape, a3.shape)

() (2,) (2, 2) (2, 2, 3)


### 3-2. 다차원 배열 다루기

In [56]:
# 3차원 배열에서 첫 번째 행렬 필터링
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
# 3차원 배열에서 첫 번째 행렬의 두 번째 행 필터링
a3[0, 1]

array([4, 5, 6])

In [58]:
# 3차원 배열에서 첫 번째 행렬의 두 번째 행의 3번째 열 필터링
a3[0, 1, 2]

6

---

## 4. 데이터 정제

### 4-1. 결측치(NaN)

In [59]:
# pandas 패키지 불러오기 및 pd라는 약어로 지칭하기
import pandas as pd  

In [60]:
# read_csv() 함수 활용 데이터 셋 불러오기
air = pd.read_csv('ch3-1.csv')

In [61]:
air

MMDDHH  PM10  PM25     O3    NO2   CO    SO2
0   06-01-01  28.0  18.0  0.039  0.009  0.3  0.002
1   06-01-02  19.0  14.0  0.041  0.007  0.3  0.002
2   06-01-03  15.0  13.0  0.043  0.006  0.3  0.002
3   06-01-04  16.0  13.0  0.042  0.006  0.3  0.002
4   06-01-05  14.0  11.0  0.041  0.008  0.3  0.003
5   06-01-06  14.0  10.0  0.040  0.009  0.3  0.003
6   06-01-07  15.0  10.0  0.038  0.014  0.3  0.002
7   06-01-08  20.0  10.0  0.034  0.019  0.3  0.002
8   06-01-09  28.0  15.0  0.032  0.022  0.4  0.003
9   06-01-10  28.0  12.0  0.035  0.017  0.4  0.003
10  06-01-11  29.0   9.0  0.038  0.015  0.4  0.003
11  06-01-12  32.0  11.0  0.039  0.012  0.3  0.003
12  06-01-13  32.0  11.0  0.038  0.015  0.3  0.003
13  06-01-14   NaN   NaN    NaN    NaN  NaN    NaN
14  06-01-15   NaN   NaN    NaN    NaN  NaN    NaN
15  06-01-16   NaN   NaN  0.038  0.020  0.4  0.003
16  06-01-17  27.0  12.0  0.041  0.022  0.4  0.003
17  06-01-18  24.0  14.0  0.048  0.016  0.4  0.003
18  06-01-19  25.0  12.0  0.048  0.014  0.3  0.003
19  06-01-20  26.0  14.0  0.043  0.020  0.4  0.003
20  06-01-21  28.0  15.0  0.049  0.017  0.4  0.003
21  06-01-22  25.0  13.0  0.045  0.020  0.4  0.003
22  06-01-23  29.0  14.0  0.035  0.023  0.4  0.003
23  06-01-24  25.0  15.0  0.028  0.027  0.4  0.003

#### ① 결측치 확인하기

In [62]:
# 결측치 확인하기1
air.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   MMDDHH  24 non-null     object 
 1   PM10    21 non-null     float64
 2   PM25    21 non-null     float64
 3   O3      22 non-null     float64
 4   NO2     22 non-null     float64
 5   CO      22 non-null     float64
 6   SO2     22 non-null     float64
dtypes: float64(6), object(1)
memory usage: 1.4+ KB


In [63]:
# 결측치 확인하기2
air.isnull()

MMDDHH   PM10   PM25     O3    NO2     CO    SO2
0    False  False  False  False  False  False  False
1    False  False  False  False  False  False  False
2    False  False  False  False  False  False  False
3    False  False  False  False  False  False  False
4    False  False  False  False  False  False  False
5    False  False  False  False  False  False  False
6    False  False  False  False  False  False  False
7    False  False  False  False  False  False  False
8    False  False  False  False  False  False  False
9    False  False  False  False  False  False  False
10   False  False  False  False  False  False  False
11   False  False  False  False  False  False  False
12   False  False  False  False  False  False  False
13   False   True   True   True   True   True   True
14   False   True   True   True   True   True   True
15   False   True   True  False  False  False  False
16   False  False  False  False  False  False  False
17   False  False  False  False  False  False  False
18   False  False  False  False  False  False  False
19   False  False  False  False  False  False  False
20   False  False  False  False  False  False  False
21   False  False  False  False  False  False  False
22   False  False  False  False  False  False  False
23   False  False  False  False  False  False  False

In [64]:
# 결측치 확인하기3
air.isnull().sum()

MMDDHH    0
PM10      3
PM25      3
O3        2
NO2       2
CO        2
SO2       2
dtype: int64

#### ② 결측치 제거하기

In [65]:
# 결측치 제거(axis = 0 : 행 제거, axis = 1 : 열 제거)
air_d = air.dropna(axis=0)

In [66]:
air_d

MMDDHH  PM10  PM25     O3    NO2   CO    SO2
0   06-01-01  28.0  18.0  0.039  0.009  0.3  0.002
1   06-01-02  19.0  14.0  0.041  0.007  0.3  0.002
2   06-01-03  15.0  13.0  0.043  0.006  0.3  0.002
3   06-01-04  16.0  13.0  0.042  0.006  0.3  0.002
4   06-01-05  14.0  11.0  0.041  0.008  0.3  0.003
5   06-01-06  14.0  10.0  0.040  0.009  0.3  0.003
6   06-01-07  15.0  10.0  0.038  0.014  0.3  0.002
7   06-01-08  20.0  10.0  0.034  0.019  0.3  0.002
8   06-01-09  28.0  15.0  0.032  0.022  0.4  0.003
9   06-01-10  28.0  12.0  0.035  0.017  0.4  0.003
10  06-01-11  29.0   9.0  0.038  0.015  0.4  0.003
11  06-01-12  32.0  11.0  0.039  0.012  0.3  0.003
12  06-01-13  32.0  11.0  0.038  0.015  0.3  0.003
16  06-01-17  27.0  12.0  0.041  0.022  0.4  0.003
17  06-01-18  24.0  14.0  0.048  0.016  0.4  0.003
18  06-01-19  25.0  12.0  0.048  0.014  0.3  0.003
19  06-01-20  26.0  14.0  0.043  0.020  0.4  0.003
20  06-01-21  28.0  15.0  0.049  0.017  0.4  0.003
21  06-01-22  25.0  13.0  0.045  0.020  0.4  0.003
22  06-01-23  29.0  14.0  0.035  0.023  0.4  0.003
23  06-01-24  25.0  15.0  0.028  0.027  0.4  0.003

#### ③ 결측치 평균값으로 대체하기

In [67]:
# 결측치 평균대체를 위해 평균 확인
air.mean()

PM10    23.761905
PM25    12.666667
O3       0.039773
NO2      0.015364
CO       0.350000
SO2      0.002727
dtype: float64

In [68]:
# 평균값으로 결측치 대체
air_m = air.fillna(air.mean())

In [69]:
air_m

MMDDHH       PM10       PM25        O3       NO2    CO       SO2
0   06-01-01  28.000000  18.000000  0.039000  0.009000  0.30  0.002000
1   06-01-02  19.000000  14.000000  0.041000  0.007000  0.30  0.002000
2   06-01-03  15.000000  13.000000  0.043000  0.006000  0.30  0.002000
3   06-01-04  16.000000  13.000000  0.042000  0.006000  0.30  0.002000
4   06-01-05  14.000000  11.000000  0.041000  0.008000  0.30  0.003000
5   06-01-06  14.000000  10.000000  0.040000  0.009000  0.30  0.003000
6   06-01-07  15.000000  10.000000  0.038000  0.014000  0.30  0.002000
7   06-01-08  20.000000  10.000000  0.034000  0.019000  0.30  0.002000
8   06-01-09  28.000000  15.000000  0.032000  0.022000  0.40  0.003000
9   06-01-10  28.000000  12.000000  0.035000  0.017000  0.40  0.003000
10  06-01-11  29.000000   9.000000  0.038000  0.015000  0.40  0.003000
11  06-01-12  32.000000  11.000000  0.039000  0.012000  0.30  0.003000
12  06-01-13  32.000000  11.000000  0.038000  0.015000  0.30  0.003000
13  06-01-14  23.761905  12.666667  0.039773  0.015364  0.35  0.002727
14  06-01-15  23.761905  12.666667  0.039773  0.015364  0.35  0.002727
15  06-01-16  23.761905  12.666667  0.038000  0.020000  0.40  0.003000
16  06-01-17  27.000000  12.000000  0.041000  0.022000  0.40  0.003000
17  06-01-18  24.000000  14.000000  0.048000  0.016000  0.40  0.003000
18  06-01-19  25.000000  12.000000  0.048000  0.014000  0.30  0.003000
19  06-01-20  26.000000  14.000000  0.043000  0.020000  0.40  0.003000
20  06-01-21  28.000000  15.000000  0.049000  0.017000  0.40  0.003000
21  06-01-22  25.000000  13.000000  0.045000  0.020000  0.40  0.003000
22  06-01-23  29.000000  14.000000  0.035000  0.023000  0.40  0.003000
23  06-01-24  25.000000  15.000000  0.028000  0.027000  0.40  0.003000

#### ④ 결측치 중앙값으로 대체하기

In [70]:
# 중앙값 확인
air.median()

PM10    25.0000
PM25    13.0000
O3       0.0395
NO2      0.0155
CO       0.3500
SO2      0.0030
dtype: float64

In [71]:
# 중앙값으로 결측치 대체
air_md = air.fillna(air.median())

In [72]:
air_md

MMDDHH  PM10  PM25      O3     NO2    CO    SO2
0   06-01-01  28.0  18.0  0.0390  0.0090  0.30  0.002
1   06-01-02  19.0  14.0  0.0410  0.0070  0.30  0.002
2   06-01-03  15.0  13.0  0.0430  0.0060  0.30  0.002
3   06-01-04  16.0  13.0  0.0420  0.0060  0.30  0.002
4   06-01-05  14.0  11.0  0.0410  0.0080  0.30  0.003
5   06-01-06  14.0  10.0  0.0400  0.0090  0.30  0.003
6   06-01-07  15.0  10.0  0.0380  0.0140  0.30  0.002
7   06-01-08  20.0  10.0  0.0340  0.0190  0.30  0.002
8   06-01-09  28.0  15.0  0.0320  0.0220  0.40  0.003
9   06-01-10  28.0  12.0  0.0350  0.0170  0.40  0.003
10  06-01-11  29.0   9.0  0.0380  0.0150  0.40  0.003
11  06-01-12  32.0  11.0  0.0390  0.0120  0.30  0.003
12  06-01-13  32.0  11.0  0.0380  0.0150  0.30  0.003
13  06-01-14  25.0  13.0  0.0395  0.0155  0.35  0.003
14  06-01-15  25.0  13.0  0.0395  0.0155  0.35  0.003
15  06-01-16  25.0  13.0  0.0380  0.0200  0.40  0.003
16  06-01-17  27.0  12.0  0.0410  0.0220  0.40  0.003
17  06-01-18  24.0  14.0  0.0480  0.0160  0.40  0.003
18  06-01-19  25.0  12.0  0.0480  0.0140  0.30  0.003
19  06-01-20  26.0  14.0  0.0430  0.0200  0.40  0.003
20  06-01-21  28.0  15.0  0.0490  0.0170  0.40  0.003
21  06-01-22  25.0  13.0  0.0450  0.0200  0.40  0.003
22  06-01-23  29.0  14.0  0.0350  0.0230  0.40  0.003
23  06-01-24  25.0  15.0  0.0280  0.0270  0.40  0.003